# Generated by Django 5.1.1 on 2026-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button_text',
            field=models.CharField(blank=True, default='Shop Now', help_text='Leave blank to make the entire slide clickable without showing a button.', max_length=50),
        ),
    ]
